[package]
name = "salps-tool"
version = "0.1.0"
edition = "2021"

description = "salps front end"

author = "parchment"
license = "MIT"
readme = "readme.md"
repository = "https://github.com/wainggan/salps-tool"

[dependencies.salps]
version = ">= 0.0.0"
path = "lib"
